openapi: 3.0.0
info:
  title: T-Shirt Store Docs
  description: Backend for T-Shirt Branding and Selling.
  version: 1.1.0
  contact: 
    email: khalid.datamax@gmail.com
    url: "https://codeforces.com/profile/Khalid_Faisal"

# servers:
#   - url: http://localhost:4000/api/v1
#     description: localhost version of social app
#   - url: https://localhost:4000/api/v1
#     description: localhost version of social app - dummy (doesn't work)

servers:
  - url: "{protocol}://localhost:4000/api/{version}/"
    description: localhost server 
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:         # https://swagger.io/docs/specification/authentication/cookie-authentication/
      type: apiKey
      in: cookie
      name: token   
    bearerAuth:            # https://swagger.io/docs/specification/authentication/bearer-authentication/
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags: 
        - Test
      summery: This endpoint is to test the environment only!
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad Request
        500:
          description: Internal server error